var trans = {
 en: {
  html: {lang:'en'},
  body: {dir: 'ltr'},
  title: {textContent: 'Activity Editor'},
  'menu-load': { textContent: 'Load', title: 'Load program from file' },
  'menu-save': { textContent: 'Save', title: 'Save program to file' },
  'menu-run': { textContent: 'Run', title: 'Execute the current program' },
  'menu-add-task': { textContent: 'Add Task', title: 'Create a new task' },
  'tab-main': { textContent: 'Main', title: 'Main settings' },
  'tab-tasks': { textContent: 'Tasks', title: 'View and edit all tasks' },
  'tab-schedule': { textContent: 'Schedule', title: 'Schedule configuration' },
  'tab-preview': { textContent: 'Preview', title: 'Preview the program' },
  'menu-all-tasks': { textContent: 'All Tasks', title: 'Show all tasks' },
  'menu-clear': { textContent: 'Clear', title: 'Clear all tasks' },
  'menu-add-slot': { textContent: 'Add Slot', title: 'Add an empty slot' },
  'main-title': { textContent: 'Title', title: 'Program title' },
  'main-lang': { textContent: 'Language', title: 'UI Language' },
  'main-bg-img': { textContent: 'Default Background Image', title: 'Set default background image' },
  'main-bg-snd': { textContent: 'Default Background Sound', title: 'Set default background sound' },
  'log-utterances': { textContent: 'Display spoken texts', title: 'Log TTS output to console' },
  'announce-all-completed': { textContent: 'Announce "all tasks completed"', title: 'Announce when all tasks are done' },
  'task-name': { textContent: 'Task Name', title: 'Name of the task' },
  'duration': { textContent: 'Duration', title: 'Task duration' },
  'hours': { textContent: 'HH', title: 'Hours' },
  'minutes': { textContent: 'MM', title: 'Minutes' },
  'seconds': { textContent: 'SS', title: 'Seconds' },
  'background-image': { textContent: 'Background Image', title: 'Select background image' },
  'background-sound': { textContent: 'Background Sound', title: 'Select background sound' },
  'announce-started': { textContent: 'Announce the starting of the task', title: 'TTS: "[Task name] started"' },
  'announce-duration': { textContent: 'Announce duration', title: 'TTS: "Total duration [time]"' },
  'announce-elapsed': { textContent: 'Announce "elapsed duration"', title: 'TTS: "[X] seconds elapsed"' },
  'announce-remaining': { textContent: 'Announce "remaining duration"', title: 'TTS: "[X] seconds remaining"' },
  'between': { textContent: ' between ' },
  'start': { textContent: 'start' },
  'end': { textContent: 'end' },
  'sec': { textContent: 's' },
  'and': { textContent: ' and ' },
  'every': { textContent: ' every ' },
  'task': { textContent: 'Task' },
  'tasks': { textContent: 'Tasks'},
  'schedule': { textContent: 'Schedule' },
  'repetitions': { textContent: 'Repetitions' },
  'media-assets': { textContent: 'Media Assets' },
  'total-duration': { textContent: 'Total Duration' },
  'total-size': { textContent: 'Total Size' },
  'images': { textContent: 'Images' },
  'sounds': { textContent: 'Sounds' },
  'media': { textContent: 'Media' },
  'add-image': { textContent: 'Add Image' },
  'add-sound': { textContent: 'Add Sound' },
  'remove-media': { textContent: 'Remove' },
  'at': { textContent: 'At' },
  'announce-next': { textContent: 'Announce next task' },
  'announce-time': { textContent: 'Announce current time' },
  'add-action': { textContent: 'Add Action', title: 'Add an action to this task' },
  'action-sound': { textContent: 'Sound', title: 'Play a sound' },
  'action-message': { textContent: 'Message', title: 'Show a message' },
  'action-predefined': { textContent: 'Predefined', title: 'Use predefined action' },
  'action-count': { textContent: 'Count', title: 'Add counter action' },
  'sound-id':{textContent: 'Sound ID'},
  'message':{textContent: 'Message'},
  'count-from': { textContent: 'from', title: 'Start value' },
  'count-to': { textContent: 'to', title: 'End value' },
  'count-step': { textContent: 'in steps of', title: 'Increment step' },
  'count-every': { textContent: 'every', title: 'Interval between counts' },
  'on-completion': { textContent: 'On completion', title: 'Actions when task ends' },
  'ticks': { textContent: 'ticks', title: 'Play tick sound' },
  'tick': { textContent: 'Tick', title: 'Play tick sound' },
  'beep': { textContent: 'Beep', title: 'Play beep' },
  'announce-completed': { textContent: 'Announce the completion of the task', title: 'TTS: "[Task name] completed"' },
  'seconds-type': { textContent: 'Seconds / Action Type', title: 'Time and action type' },
  'test-task': { title: 'Test this task' },
  'up': { textContent: 'Up', title: 'Move task up' },
  'down': { textContent: 'Down', title: 'Move task down' },
  'duplicate': { textContent: 'Duplicate', title: 'Duplicate task' },
  'remove': { textContent: 'Remove', title: 'Remove task' },
  'undo': { textContent: 'Undo', title: 'Undo last action' },
  'redo': { textContent: 'Redo', title: 'Redo last undone action' },
  'play': { textContent: 'Play' },
  'display': { textContent: 'Display' },
  'speak': { textContent: 'Speak' },
  "from-file":{label:"From File"},
  "from-json-file":{textContent: 'JSON File'},
  "from-html-file":{textContent: 'HTML File'},
  "from-preset":{label: 'Presets / Examples'},
  "from-exam":{textContent: 'Example: English Exam'},
  "from-hiit":{textContent: 'Example: HIIT Sport'},
  "about-title":{"innerHTML":"🎯 About T Tasks Timer"},
  "about-version":{"innerHTML":"Version"},
  "about-issue":{"innerHTML":"Issue Tracker"},
  "about-pitch":{"innerHTML":"<strong>T Tasks Timer</strong> is a lightweight, privacy-focused task runner and sequence scheduler designed to automate your time-blocks."},
  "about-how":{"innerHTML":"How It Works"},
  "about-li-1":{"innerHTML":"<strong>⚙️ Create Tasks & Actions:</strong> Build custom tasks. Each task contains individual actions with precise durations, custom spoken texts, or background alerts."},
  "about-li-2":{"innerHTML":"<strong>🗓️ Design Your Schedule:</strong> Mix, match, and loop! Sequence your tasks in the timeline in any order you want (e.g., <em>Task 1</em> → <em>Task 1</em> → <em>Task 2</em>)."},
  "about-li-3":{"innerHTML":"<strong>⚡ Run & Execute:</strong> Watch your custom sequence execute with live countdowns, background audio, and text-to-speech announcements."},
  "about-app":{"innerHTML":"This app is <strong>100% Free and Open Source</strong> under the <strong>Apache 2.0 License</strong>. It runs entirely locally in your browser and uses your device's capabilities."},
  "about-source":{"innerHTML":"💻 View Source Code on GitHub"},
  "about-author":{"innerHTML":"Created by TROUZINE Abderrezzaq © 2026"},
 },

 fr: {
  html: {lang:'fr'},
  body: {dir: 'ltr'},
  title: {textContent: "Editeur d'activité"},
  'menu-load': { textContent: 'Charger', title: 'Charger un programme depuis un fichier' },
  'menu-save': { textContent: 'Enregistrer', title: 'Enregistrer le programme dans un fichier' },
  'menu-run': { textContent: 'Exécuter', title: 'Exécuter le programme actuel' },
  'menu-add-task': { textContent: 'Ajouter une tâche', title: 'Créer une nouvelle tâche' },
  'tab-main': { textContent: 'Principal', title: 'Paramètres principaux' },
  'tab-tasks': { textContent: 'Tâches', title: 'Voir et modifier toutes les tâches' },
  'tab-schedule': { textContent: 'Planification', title: 'Configuration de la planification' },
  'tab-preview': { textContent: 'Aperçu', title: 'Aperçu du programme' },
  'menu-all-tasks': { textContent: 'Toutes les tâches', title: 'Afficher toutes les tâches' },
  'menu-clear': { textContent: 'Effacer tout', title: 'Effacer toutes les tâches' },
  'menu-add-slot': { textContent: 'Ajouter un emplacement', title: 'Ajouter un emplacement vide' },
  'main-title': { textContent: 'Titre', title: 'Titre du programme' },
  'main-lang': { textContent: 'Langue', title: 'Langue de l\'interface' },
  'main-bg-img': { textContent: 'Image de fond par défaut', title: 'Définir l\'image de fond par défaut' },
  'main-bg-snd': { textContent: 'Son de fond par défaut', title: 'Définir le son de fond par défaut' },
  'log-utterances': { textContent: 'Afficher les textes parlés', title: 'Enregistrer la sortie TTS dans la console' },
  'announce-all-completed': { textContent: 'Annoncer "toutes les tâches terminées"', title: 'Annoncer quand toutes les tâches sont terminées' },
  'task-name': { textContent: 'Nom de la tâche', title: 'Nom de la tâche' },
  'duration': { textContent: 'Durée', title: 'Durée de la tâche' },
  'hours': { textContent: 'HH', title: 'Heures' },
  'minutes': { textContent: 'MM', title: 'Minutes' },
  'seconds': { textContent: 'SS', title: 'Secondes' },
  'background-image': { textContent: 'Image de fond', title: 'Sélectionner une image de fond' },
  'background-sound': { textContent: 'Son de fond', title: 'Sélectionner un son de fond' },
  'announce-started': { textContent: 'Annoncer le démarrage de la tâche', title: 'Synthèse vocale : "[Nom] commencée"' },
  'announce-duration': { textContent: 'Annoncer la durée', title: 'Synthèse vocale : "Durée totale [temps]"' },
  'announce-elapsed': { textContent: 'Annoncer "temps écoulé"', title: 'TTS: "[X] secondes écoulées"' },
  'announce-remaining': { textContent: 'Annoncer "temps restant"', title: 'TTS: "[X] secondes restantes"' },
  'between': { textContent: ' entre ' },
  'start': { textContent: 'début' },
  'end': { textContent: 'fin' },
  'sec': { textContent: 's' },
  'and': { textContent: ' et ' },
  'every': { textContent: ' chaque ' },
  'at': { textContent: 'A' },
  'task': { textContent: 'Tâche' },
  'tasks': { textContent: 'Tâches'},
  'schedule': { textContent: 'Planification' },
  'repetitions': { textContent: 'Répétitions' },
  'media-assets': { textContent: 'Actifs Médiatiques' },
  'total-duration': { textContent: 'Durée Totale' },
  'total-size': { textContent: 'Taille Totale' },
  'images': { textContent: 'Images' },
  'sounds': { textContent: 'Sons' },
  'media': { textContent: 'Média' },
  'add-image': { textContent: 'Ajouter une image' },
  'add-sound': { textContent: 'Ajouter un son' },
  'remove-media': { textContent: 'Effacer' },
  'announce-next': { textContent: 'Annoncer la prochaine tâche' },
  'announce-time': { textContent: "Annoncer l'heure actuelle" },
  'add-action': { textContent: 'Ajouter une action', title: 'Ajouter une action à cette tâche' },
  'action-sound': { textContent: 'Son', title: 'Jouer un son' },
  'action-message': { textContent: 'Message', title: 'Afficher un message' },
  'action-predefined': { textContent: 'Prédéfini', title: 'Utiliser une action prédéfinie' },
  'action-count': { textContent: 'Compteur', title: 'Ajouter une action de comptage' },
  'sound-id':{textContent: 'ID Son'},
  'message':{textContent: 'Message'},
  'count-from': { textContent: 'de', title: 'Valeur de départ' },
  'count-to': { textContent: 'à', title: 'Valeur de fin' },
  'count-step': { textContent: 'en sauts de', title: 'Pas d\'incrémentation' },
  'count-every': { textContent: 'toutes les', title: 'Intervalle entre les comptages' },
  'on-completion': { textContent: 'À la fin', title: 'Actions lorsque la tâche se termine' },
  'ticks': { textContent: 'tics', title: 'Jouer un son de tic-tac' },
  'tick': { textContent: 'Tic', title: 'Jouer un son de tic-tac' },
  'beep': { textContent: 'Bip', title: 'Jouer un bip' },
  'announce-completed': { textContent: "Annoncer l'achèvement de la tâche", title: 'Synthèse vocale : "[Nom] terminée"' },
  'seconds-type': { textContent: 'Secondes / Type d\'action', title: 'Temps et type d\'action' },
  'test-task': { title: 'Tester cette tâche' },
  'up': { textContent: 'Haut', title: 'Déplacer la tâche vers le haut' },
  'down': { textContent: 'Bas', title: 'Déplacer la tâche vers le bas' },
  'duplicate': { textContent: 'Dupliquer', title: 'Dupliquer la tâche' },
  'remove': { textContent: 'Supprimer', title: 'Supprimer la tâche' },
  'undo': { textContent: 'Annuler', title: 'Annuler la dernière action' },
  'redo': { textContent: 'Rétablir', title: 'Rétablir la dernière action annulée' },
  'play': { textContent: 'Jouer' },
  'display': { textContent: 'Afficher' },
  'speak': { textContent: 'Lire' },
  "from-file":{label:"fichier"},
  "from-json-file":{textContent: 'JSON'},
  "from-html-file":{textContent: 'HTML'},
  "from-preset":{label: 'Préréglages / Exemples'},
  "from-exam":{textContent: "Exemple : Examen d'anglais"},
  "from-hiit":{textContent: 'Exemple : HIIT Sport'},
  "about-title":{"innerHTML":"🎯 À propos de T Tasks Timer"},
  "about-version":{"innerHTML":"Version"},
  "about-issue":{"innerHTML":"Suivi des problèmes"},
  "about-pitch":{"innerHTML":"<strong>T Tasks Timer</strong> est un gestionnaire de tâches et un planificateur de séquences HTML5 conçu pour automatiser vos plages horaires."},
  "about-how":{"innerHTML":"Fonctionnement"},
  "about-li-1":{"innerHTML":"<strong>⚙️ Création de tâches et d'actions&nbsp;:</strong> Créez des tâches personnalisées. Chaque tâche comprend des actions individuelles avec des durées précises, des annonces vocales personnalisées ou des alertes en arrière-plan."},
  "about-li-2":{"innerHTML":"<strong>🗓️ Personnalisation de votre planning&nbsp;:</strong> Combinez, associez et bouclez ! Organisez vos tâches dans l'ordre de votre choix (par exemple : <em>Tâche 1</em> → <em>Tâche 1</em> → <em>Tâche 2</em>)."},
  "about-li-3":{"innerHTML":"<strong>⚡ Exécution&nbsp;:</strong> Suivez l'exécution de votre séquence personnalisée grâce aux comptes à rebours en direct, aux annonces audio en arrière-plan et à la synthèse vocale."},
  "about-app":{"innerHTML":"Cette application est <strong>100 % gratuite et Open Source</strong> sous <strong>licence Apache 2.0</strong>. Elle s'exécute entièrement en local dans votre navigateur et utilise les capacités de votre appareil."},
  "about-source":{"innerHTML":"💻 Consulter le code source sur GitHub"},
  "about-author":{"innerHTML":"Créé par TROUZINE Abderrezzaq © 2026"},
 },
 
 ar: {
  html: {lang:'ar'},
  body: {dir: 'rtl'},
  title: {textContent: 'محرر الأنشطة'},
  'menu-load': { textContent: 'تحميل', title: 'تحميل برنامج من ملف' },
  'menu-save': { textContent: 'حفظ', title: 'حفظ البرنامج إلى ملف' },
  'menu-run': { textContent: 'تشغيل', title: 'تنفيذ البرنامج الحالي' },
  'menu-add-task': { textContent: 'إضافة مهمة', title: 'إنشاء مهمة جديدة' },
  'tab-main': { textContent: 'الرئيسية', title: 'الإعدادات الرئيسية' },
  'tab-tasks': { textContent: 'المهام', title: 'عرض وتعديل جميع المهام' },
  'tab-schedule': { textContent: 'التخطيط', title: 'إعدادات الجدولة' },
  'tab-preview': { textContent: 'معاينة', title: 'معاينة البرنامج' },
  'menu-all-tasks': { textContent: 'جميع المهام', title: 'عرض جميع المهام' },
  'menu-clear': { textContent: 'مسح الكل', title: 'مسح جميع المهام' },
  'menu-add-slot': { textContent: 'إضافة مكان', title: 'إضافة مكان فارغ' },
  'main-title': { textContent: 'العنوان', title: 'عنوان البرنامج' },
  'main-lang': { textContent: 'اللغة', title: 'لغة الواجهة' },
  'main-bg-img': { textContent: 'صورة الخلفية الافتراضية', title: 'تعيين صورة الخلفية الافتراضية' },
  'main-bg-snd': { textContent: 'صوت الخلفية الافتراضي', title: 'تعيين صوت الخلفية الافتراضي' },
  'log-utterances': { textContent: 'عرض النصوص المنطوقة', title: 'تسجيل مخرجات تحويل النص إلى كلام في وحدة التحكم' },
  'announce-all-completed': { textContent: 'أعلن "اكتملت جميع المهام"', title: 'الإعلان عند اكتمال جميع المهام' },
  'task-name': { textContent: 'اسم المهمة', title: 'اسم المهمة' },
  'duration': { textContent: 'المدة', title: 'مدة المهمة' },
  'hours': { textContent: 'س', title: 'ساعات' },
  'minutes': { textContent: 'د', title: 'دقائق' },
  'seconds': { textContent: 'ث', title: 'ثواني' },
  'background-image': { textContent: 'صورة الخلفية', title: 'اختيار صورة الخلفية' },
  'background-sound': { textContent: 'صوت الخلفية', title: 'اختيار صوت الخلفية' },
  'announce-started': { textContent: 'الإعلان عن ابتداء المهمة', title: 'تحويل النص إلى كلام: "[اسم المهمة] بدأت"' },
  'announce-duration': { textContent: 'أعلن المدة', title: 'تحويل النص إلى كلام: "المدة الإجمالية [الوقت]"' },
  'announce-elapsed': { textContent: 'الإعلان عن "المدة المنقضية"', title: 'TTS: "انقضت [س] ثواني"' },
  'announce-remaining': { textContent: 'الإعلان عن "المدة المتبقية"', title: 'TTS: "تبقى [س] ثواني"' },
  'between': { textContent: ' بين ' },
  'start': { textContent: 'البداية' },
  'end': { textContent: 'النهاية' },
  'sec': { textContent: 'ث' },
  'and': { textContent: ' و ' },
  'every': { textContent: ' كل ' },
  'at': { textContent: 'عند' },
  'task': { textContent: 'المهمة' },
  'tasks': { textContent: 'المهام'},
  'schedule': { textContent: 'التخطيط' },
  'repetitions': { textContent: 'التكرار' },
  'media-assets': { textContent: 'أصول الوسائط' },
  'total-duration': { textContent: 'المدة الإجمالية' },
  'total-size': { textContent: 'الحجم الإجمالي' },
  'images': { textContent: 'صور' },
  'sounds': { textContent: 'أصوات' },
  'media': { textContent: 'الكل' },
  'add-image': { textContent: 'إضافة صورة' },
  'add-sound': { textContent: 'إضافة صوت' },
  'remove-media': { textContent: 'حذف' },
  'announce-next': { textContent: 'الإعلان بالمهمة التالية' },
  'announce-time': { textContent: 'الإعلان بالوقت الحالي' },
  'add-action': { textContent: 'إضافة إجراء', title: 'إضافة إجراء إلى هذه المهمة' },
  'action-sound': { textContent: 'صوت', title: 'تشغيل صوت' },
  'action-message': { textContent: 'رسالة', title: 'عرض رسالة' },
  'action-predefined': { textContent: 'محدد مسبقاً', title: 'استخدام إجراء محدد مسبقاً' },
  'action-count': { textContent: 'عداد', title: 'إضافة إجراء عداد' },
  'sound-id':{textContent: 'معرّف الصوت'},
  'message':{textContent: 'الرسالة'},
  'count-from': { textContent: 'من', title: 'قيمة البداية' },
  'count-to': { textContent: 'إلى', title: 'قيمة النهاية' },
  'count-step': { textContent: 'بفارق', title: 'خطوة الزيادة' },
  'count-every': { textContent: 'كل', title: 'الفاصل الزمني بين العدات' },
  'on-completion': { textContent: 'عند الإكمال', title: 'الإجراءات عند انتهاء المهمة' },
  'ticks': { textContent: 'دقات', title: 'تشغيل صوت تكتكة' },
  'tick': { textContent: 'دقة', title: 'تشغيل صوت تكتكة' },
  'beep': { textContent: 'صفير', title: 'تشغيل صفير' },
  'announce-completed': { textContent: 'الإعلان عن اكتمال المهمة', title: 'تحويل النص إلى كلام: "[اسم المهمة] اكتملت"' },
  'seconds-type': { textContent: 'ثواني / نوع الإجراء', title: 'الوقت ونوع الإجراء' },
  'test-task': { title: 'اختبار هذه المهمة' },
  'up': { textContent: 'أعلى', title: 'نقل المهمة لأعلى' },
  'down': { textContent: 'أسفل', title: 'نقل المهمة لأسفل' },
  'duplicate': { textContent: 'استنساخ', title: 'نسخ المهمة' },
  'remove': { textContent: 'حذف', title: 'حذف المهمة' },
  'undo': { textContent: 'تراجع', title: 'التراجع عن آخر إجراء' },
  'redo': { textContent: 'إعادة', title: 'إعادة آخر إجراء تم التراجع عنه' },
  'play': { textContent: 'تشغيل' },
  'display': { textContent: 'عرض' },
  'speak': { textContent: 'قراءة' },
  "from-file":{label:"من ملف"},
  "from-json-file":{textContent: 'ملف JSON'},
  "from-html-file":{textContent: 'ملف HTML'},
  "from-preset":{label: 'إعدادات مسبقة / أمثلة'},
  "from-exam":{textContent: "مثال: امتحان اللغة الإنجليزية"},
  "from-hiit":{textContent: 'مثال: رياضة HIIT'},
  "about-title":{"innerHTML":"🎯 حول مؤقت مهام T Tasks Timer"},
  "about-version":{"innerHTML":"النسخة"},
  "about-issue":{"innerHTML":"نظام تتبع المشكلات"},
  "about-pitch":{"innerHTML":"<strong>مؤقت مهام T Tasks Timer</strong>هو تطبيق HTML5 لتشغيل المهام وجدولة التسلسلات، مصمم لأتمتة فتراتك الزمنية. "},
  "about-how":{"innerHTML":"كيف يعمل؟"},
  "about-li-1":{"innerHTML":"<strong>⚙️ إنشاء المهام والإجراءات:</strong> أنشئ مهامًا مخصصة. تحتوي كل مهمة على إجراءات فردية بمدد زمنية دقيقة، ونصوص صوتية مخصصة، أو تنبيهات في الخلفية."},
  "about-li-2":{"innerHTML":"<strong>🗓️ تصميم جدولك:</strong> امزج، وطابق، وكرر! رتب مهامك بأي ترتيب تريده (مثلاً: <em>المهمة 1</em> ← <em>المهمة 1</em> ← <em>المهمة 2</em>)."},
  "about-li-3":{"innerHTML":"<strong>⚡ التشغيل والتنفيذ:</strong> شاهد تسلسلك المخصص وهو يُنفذ مع عد تنازلي مباشر، وصوت في الخلفية، وإعلانات تحويل النص إلى كلام."},
  "about-app":{"innerHTML":"هذا التطبيق <strong>مجاني بالكامل ومفتوح المصدر</strong> بموجب <strong>ترخيص Apache 2.0</strong>. يعمل بالكامل محليًا في متصفحك ويستفيد من إمكانيات جهازك."},
  "about-source":{"innerHTML":"💻 عرض الكود المصدري على GitHub"},
  "about-author":{"innerHTML":"من تطوير تروزين عبد الرزاق © 2026"},
 }
};
